// frontend/src/views/events/EventDetails.vue
<template>
  <div class="grid grid-cols-2 my-5" >
    <article v-if="isdata">
      <img :src="event_data.photo" id="event-image" alt="event-image" />
    </article>
    <section id="event-content">
      <h1 class="text-4xl font-bold my-3"><a :href="event_data.website_url">{{event_data.title}}</a></h1>
      <p class="my-4 w-4/5">
        {{event_data.description}}
      </p>
      
      <h4 class="text-gray-600 my-2" v-if="isdata">
        <div>
          <svg class="h-8 w-8 text-red-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/>
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/>
          </svg>
          <span>
            {{event_data.venue}}
          </span>
        </div>
      </h4>

      <h5 class="text-gray-600 my-2" v-if="isdata">
        <div>
          <svg class="h-8 w-8 text-red-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  
            <path stroke="none" d="M0 0h24v24H0z"/>  <rect x="4" y="5" width="16" height="16" rx="2" />  
            <line x1="16" y1="3" x2="16" y2="7" />  <line x1="8" y1="3" x2="8" y2="7" />  
            <line x1="4" y1="11" x2="20" y2="11" />  <rect x="8" y="15" width="2" height="2" />
          </svg>
          <span>Date: <span>{{event_data.start_date}}</span> -<span>{{event_data.end_date}}</span></span>
        </div>
      </h5>

      <h5 class="text-gray-600 my-2" v-if="isdata">
        <div>
          <svg class="h-8 w-8 text-red-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
          </svg>
          <span>Time: <span>{{event_data.start_time}}</span> - <span>{{event_data.end_time}}</span></span>
        </div>
      </h5>

      <button v-if="isdata"
        class=" w-1/4 px-7 py-3 bg-primary text-white rounded text-sm font-medium hover:bg-primaryHover transition ease-in-out delay-150"
      >
        Register
      </button>
    </section>
  </div>
</template>

<script setup>
//import { ref } from 'vue';
import { ref } from '@vue/reactivity';
import router from '../../router';


  
var eid = ref(router.currentRoute.value.params.eventid)
var event_data = ref('')
var isdata = ref(false)


eventDetails()

function eventDetails(){

  fetch("http://localhost:8080/api/v1/events/"+eid.value.toString(), {
    method: "GET",
    headers: {
      // 'X-CSRFToken': token
      'Authorization': localStorage.getItem('token')
    },
    credentials: "same-origin",
  })
  .then(function (response){
    if (!response.ok) {
      alert("HTTP status " + response.status);
      return
    }
    return response.json();
  })
  .then(function (jsonResponse) {
    event_data.value = jsonResponse

    isdata.value = true
  })
  .catch(function (error) {
    console.log(error);
  });

}




</script>
<style scoped>
h4 div, h5 div{
  display: flex;
  flex-direction: row;

}

h4 div span, h5 div span{
  padding-top:5px;
  padding-left: 10px;
}

#event-content{
  display: flex;
  flex-direction: column;
}

button{
  margin-top:10%;
}

a:hover{
  color: #d1410c;
  
}
</style>

// ionic-frontend/src/pages/Events/EventDetails.tsx
import {
  IonContent,
  IonIcon,
  IonPage,
  useIonViewWillEnter,
} from "@ionic/react";
import { IonText } from "@ionic/react";
import React from "react";
import { useState } from "react";
import { location } from "ionicons/icons";
import BackButton from "../../components/BackButton";
import "./EventDetails.css";
import { useParams } from "react-router";

type EventParams = {
  eventid: string;
};

const EventDetails: React.FC = () => {
  interface Event {
    created_at: string;
    description: string;
    end_date: string;
    end_time: string;
    eventid: number;
    photo: string;
    start_date: string;
    start_time: string;
    status: string;
    title: string;
    user_id: number;
    venue: string;
    website_url: String;
  }

  const { eventid } = useParams<EventParams>();
  const [event, setEvent] = useState<Event>();
  //const token = localStorage.getItem("token");

  useIonViewWillEnter(() => {
    const token = localStorage.getItem("token");

    fetch(`http://localhost:8080/api/v1/events/${eventid}` + "", {
      method: "GET",
      headers: {
        //'X-CSRFToken': token
        Authorization: `${token}`,
      },
      credentials: "same-origin",
    })
      .then(function (response) {
        if (!response.ok) {
          alert("HTTP status " + response.status);
          return;
        }
        return response.json();
      })
      .then(function (jsonResponse: Event) {
        setEvent(jsonResponse);
      })
      .catch(function (error) {
        console.log(error);
      });
  }, []);

  return (
    <IonPage>
      <div>
        <BackButton></BackButton>
      </div>

      <IonContent className="details-container">
        <div className="event-details-top">
          <div className="event-details-mobile event-details-title">
            <IonText color="muted">
              <h1>{event?.title} </h1>
            </IonText>
          </div>

          <div className="event-details-image">
            <img src={event?.photo} className="event-image"></img>
          </div>
        </div>

        <div className="event-details-bottom">
          <div className="event-details-content">
            <div className="event-details-desktop event-details-title">
              <IonText color="muted">
                <h1>{event?.title} </h1>
              </IonText>
            </div>
            <div>
              <h5>EVENT DESCRIPTION</h5>
              <IonText className="ion-padding" color="primary">
                {event?.description}
              </IonText>
            </div>

            <div className="event-details-location">
              <h5>EVENT LOCATION</h5>
              <div>
                <IonIcon src={location} color="medium">
                  {" "}
                </IonIcon>

                <IonText color="medium">{event?.venue}</IonText>
              </div>
            </div>

            <div className="event-date-time-container">
              <div className="event-details-dates">
                <div>
                  <h5>START DATE</h5>
                  <IonText color="primary">{event?.start_date}</IonText>
                </div>

                <div>
                  <h5>START TIME</h5>
                  <IonText color="primary">{event?.start_time}</IonText>
                </div>
              </div>

              <div className="event-details-times">
                <div>
                  <h5>END DATE</h5>
                  <IonText color="primary">{event?.end_date}</IonText>
                </div>

                <div>
                  <h5>END TIME</h5>
                  <IonText color="primary">{event?.end_time}</IonText>
                </div>
              </div>
            </div>
          </div>
        </div>
      </IonContent>
    </IonPage>
  );
};

export default EventDetails;
